name: Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: olafurpg/setup-scala@v10
      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/coursier/v1
            ~/.sbt
          key: sbt-${{ hashFiles('**/build.sbt') }}
      - name: Run tests
        run: sbt +clean +test +doc
